### ISSUE TITLE
Push to npm?

### ISSUE THREAD

**Issue by tmcw** [elijahmanor/eslint-plugin-smells#1]
http://npmjs.org/eslint-plugin-smells comes up with a 404 - has this plugin been pushed to npm?

**Comment by subblue** [comment]
Same issue here.
Thanks for your js-smells talk - very useful!

**Comment by mlegenhausen** [comment]
+1

**Comment by mark-bradshaw** [comment]
Same, still.  Had to install via github url.

**Comment by mark-bradshaw** [comment]
@elijahmanor ^^

**Comment by davegomez** [comment]
+1

**Comment by jbpionnier** [comment]
- 1 for push
  very interesting

**Comment by sheppy** [comment]
+1 Saw this over at http://elijahmanor.github.io/talks/js-smells and wanted to give it a try

**Comment by tmcw** [comment]
I'm sure at this point elijah has seen this thread, so we can stop with the +1s, thx. :)

**Comment by elijahmanor** [comment]
So, I should really not filter my github emails. Sorry all, just published to npm.
